Selbstverständnis und Verankerung des Verhaltenskodex
ZaPF/Satzung_der_ZaPF pull request #32
Opened 2024-05-13 14:39 UTC by scattenlaeufer

Dies definiert ein minimales Selbstverständnis der ZaPF und verankert den schon beschlossenen Verhaltenskodex in der Satzung.

2024-05-14 10:47 UTC, Tobi-L commented
Die ZaPF ist nicht Basisdemokratisch.
Laut https://de.wikipedia.org/wiki/Basisdemokratie beinhaltet Basisdemokratisch zwingend Konsens-Prinzip:
Die ZaPF nutz das Konsenz-Prinzip nicht (Entscheidungen werden mit Mehrheiten gefällt, es gibt kein Veto)

2024-05-14 11:20 UTC, scattenlaeufer commented
Die bpb erwähnt in ihrer [Definition von Basisdemokratie](https://www.bpb.de/kurz-knapp/lexika/politiklexikon/17153/basisdemokratie/) das Konsensprinzip nicht als Voraussetzung. Auch wenn ich das jetzt nicht als Wort Gottes akzeptiere, würde ich das doch der Wikipedia vorziehen, alleine schon weil es auf eine plausiblere Quelle als "Trust Me Bro" verweist.

2024-10-29 08:19 UTC, bonko18 commented
Bin wie Tobi auch über das "basisdemokratisch" gestolpert. Würde auch sagen, dass die ZaPF nicht basisdemokratisch ist, da nur jede FS mit mindestens einer teilnehmenden Person Stimmrecht hat und nicht jede teilnehmende Person. Wohlgleich alle teilnehmenden Personen Antragsrecht haben. Ebenso setzen sich die teilnehmenden Personen (Ausnahme Helfika und  Alte Säcke) aus entsandten Personen zusammen, was wiederum nicht zwangsläufig basisdemokratisch passieren muss und meiner Meinung nach ehr nach "repräsentativdemokratisch" spricht.

2024-11-04 00:47 UTC, behrmann commented
@n4TRUAL kannst du die letzte Fassung entweder als PR gegen Björns Branch machen oder hier reinposten, damit Björn es selbst rebasen kann? Mein Verständnis aus der Ferne ist, dass die beschlossene Fassung
> Die ZaPF versteht sich als antifaschistisch, demokratisch und offen für alle Menschen, welche diese Grundsätze teilen

ist.

2024-11-04 06:54 UTC, n4TRUAL commented
Habe die fassung gerade nicht zur hand. Es wurde aber nur das basis bei basisdemokratisch gestrichen.
Sonst wie es vorgeschlagen wurde

2024-11-05 01:33 UTC, behrmann requested changes
Nach meinem Stand ist das die endgültige Fassung aus dem Plenum.

2024-11-05 01:33 UTC, behrmann commented on satzung.md
> +alle Menschen.
```suggestion
Die ZaPF versteht sich als antifaschistisch, demokratisch und offen für
alle Menschen, welche diese Grundsätze teilen.
```

2024-11-05 05:24 UTC, n4TRUAL approved these changes
True war mein Fehler dachte es wäre schon drin

2024-11-05 08:26 UTC, n4TRUAL approved these changes

2024-11-05 09:42 UTC, behrmann commented
@scattenlaeufer Magst du die drei Commits noch in einen schönen Commit mit einer vernünftigen Message squashen?

2025-04-05 18:10 UTC, merged